#!/usr/bin/env python

import rospy

from comp0037_explorer.explorer_node_wavefront_closest import ExplorerNode

if __name__ == '__main__':
    try:
        explorerNode = ExplorerNode()
        explorerNode.run()
    except rospy.ROSInterruptException:
        pass
